DHAN_CLIENT_ID = "YOUR_DHAN_CLIENT_ID"
DHAN_ACCESS_TOKEN = "YOUR_DHAN_ACCESS_TOKEN"
DHAN_BASE_URL = "https://api.dhan.co/v2"
SCRIP_MASTER_URL = "https://images.dhan.co/api-data/api-scrip-master.csv"

TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_TELEGRAM_CHAT_ID"

DB_NAME = "quant_historical_terminal.db"
THEME_BG = "#0E1117"
THEME_CARD_BG = "#1E222D"
COLOR_CALL = "#00E676"
COLOR_PUT = "#FF5252"
COLOR_NEUTRAL = "#29B6F6"
